name: Deploy PyPi

on:
  push:
    branches: ["main"]
    tags: ["v*"]

jobs:
 deploy:
    # This job will only run when a tag is pushed
    if: startsWith(github.ref, 'refs/tags/v')
    
    # It requires the lint and test jobs to complete successfully first
    needs: [lint, test]
    
    runs-on: ubuntu-latest
    
    # Grant permissions for the action to create a release
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/install-uv-action@v1

      - name: Build package
        run: uv build

      - name: Publish package to PyPI
        run: uv publish --token ${{ secrets.PYPI_API_TOKEN }}